#include "DIO_INTERFACE.h"



const PIN_Status Pin_StatusArray [PINs_Total]={
	
OUTPUT,      //PINA0
OUTPUT,		 //PINA1
INFREE,		 //PINA2
INFREE,		 //PINA3
INFREE,      //PINA4
INFREE,		 //PINA5
INFREE,		 //PINA6
INPUT,      //PINA7
OUTPUT,      //PINB0
OUTPUT,		 //PINB1
OUTPUT,		 //PINB2
OUTPUT,		 //PINB3
OUTPUT,      //PINB4  //SS
OUTPUT,		 //PINB5 //MOSI
OUTPUT,		 //PINB6  //MISO
OUTPUT,      //PINB7 //SCK
OUTPUT,      //PINC0
OUTPUT,		 //PINC1
OUTPUT,		 //PINC2
OUTPUT,		 //PINC3
OUTPUT,      //PINC4
OUTPUT,		 //PINC5
OUTPUT,		 //PINC6
OUTPUT,      //PINC7
OUTPUT,      //PIND0
OUTPUT,		 //PIND1
INPUT,		 //PIND2
INPUT,		 //PIND3
INPUT,      //PIND4
INPUT,		 //PIND5
INPUT,		 //PIND6
INPUT       //PIND7
};